## chapter 1: getting and knowin your data

In [1]:
import pandas as pd

In [2]:
pd.read_csv(filepath_or_buffer="data.tsv.txt", sep="\t")

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [3]:
order_details=pd.read_table(filepath_or_buffer="data.tsv.txt")

In [4]:
order_details

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

## 1.1 perform inital analysis

In [5]:
## function()
## attributes kku no needed for ()

In [6]:
order_details.shape

(4622, 5)

#### 


terminology alert

* Rows-observation| record
* column-features| parameters

In [7]:
order_details.isnull().sum()

order_id                 0
quantity                 0
item_name                0
choice_description    1246
item_price               0
dtype: int64

In [8]:
order_details.dtypes

order_id               int64
quantity               int64
item_name             object
choice_description    object
item_price            object
dtype: object

In [9]:
order_details.describe(include='all')

           order_id     quantity     item_name choice_description item_price
count   4622.000000  4622.000000          4622               3376       4622
unique          NaN          NaN            50               1043         78
top             NaN          NaN  Chicken Bowl        [Diet Coke]     $8.75
freq            NaN          NaN           726                134        730
mean     927.254868     1.075725           NaN                NaN        NaN
std      528.890796     0.410186           NaN                NaN        NaN
min        1.000000     1.000000           NaN                NaN        NaN
25%      477.250000     1.000000           NaN                NaN        NaN
50%      926.000000     1.000000           NaN                NaN        NaN
75%     1393.000000     1.000000           NaN                NaN        NaN
max     1834.000000    15.000000           NaN                NaN        NaN

## 1.2 find out the item sold in restaurent

In [10]:
order_details.nunique()

order_id              1834
quantity                 9
item_name               50
choice_description    1043
item_price              78
dtype: int64

In [11]:
print(order_details["item_name"].unique())

['Chips and Fresh Tomato Salsa' 'Izze' 'Nantucket Nectar'
 'Chips and Tomatillo-Green Chili Salsa' 'Chicken Bowl' 'Side of Chips'
 'Steak Burrito' 'Steak Soft Tacos' 'Chips and Guacamole'
 'Chicken Crispy Tacos' 'Chicken Soft Tacos' 'Chicken Burrito'
 'Canned Soda' 'Barbacoa Burrito' 'Carnitas Burrito' 'Carnitas Bowl'
 'Bottled Water' 'Chips and Tomatillo Green Chili Salsa' 'Barbacoa Bowl'
 'Chips' 'Chicken Salad Bowl' 'Steak Bowl' 'Barbacoa Soft Tacos'
 'Veggie Burrito' 'Veggie Bowl' 'Steak Crispy Tacos'
 'Chips and Tomatillo Red Chili Salsa' 'Barbacoa Crispy Tacos'
 'Veggie Salad Bowl' 'Chips and Roasted Chili-Corn Salsa'
 'Chips and Roasted Chili Corn Salsa' 'Carnitas Soft Tacos'
 'Chicken Salad' 'Canned Soft Drink' 'Steak Salad Bowl'
 '6 Pack Soft Drink' 'Chips and Tomatillo-Red Chili Salsa' 'Bowl'
 'Burrito' 'Crispy Tacos' 'Carnitas Crispy Tacos' 'Steak Salad'
 'Chips and Mild Fresh Tomato Salsa' 'Veggie Soft Tacos'
 'Carnitas Salad Bowl' 'Barbacoa Salad Bowl' 'Salad' 'Veggie Crispy Tacos'
 'Veggie Salad' 'Carnitas Salad']

## 1.3 give me the list of top 5 selling item

In [12]:
order_details.groupby(by="item_name")["quantity"].sum().sort_values(ascending= False).head(10)#chain method

item_name
Chicken Bowl                    761
Chicken Burrito                 591
Chips and Guacamole             506
Steak Burrito                   386
Canned Soft Drink               351
Chips                           230
Steak Bowl                      221
Bottled Water                   211
Chips and Fresh Tomato Salsa    130
Canned Soda                     126
Name: quantity, dtype: int64

## 1.3 give me the list of least selling items

In [13]:
order_details.groupby(by="item_name")["quantity"].sum().sort_values().head()

item_name
Carnitas Salad                       1
Chips and Mild Fresh Tomato Salsa    1
Veggie Crispy Tacos                  1
Crispy Tacos                         2
Salad                                2
Name: quantity, dtype: int64

## chapter 2 - data cleaning

In [14]:
order_details["item_price"].str.replace("$", "")

0        2.39
1        3.39
2        3.39
3        2.39
4       16.98
         ...
4617    11.75
4618    11.75
4619    11.25
4620     8.75
4621     8.75
Name: item_price, Length: 4622, dtype: object

In [15]:
order_details["item_price"].str.replace("$", "").astype(float)

0        2.39
1        3.39
2        3.39
3        2.39
4       16.98
        ...
4617    11.75
4618    11.75
4619    11.25
4620     8.75
4621     8.75
Name: item_price, Length: 4622, dtype: float64

In [16]:
order_details

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [17]:
order_details.dtypes

order_id               int64
quantity               int64
item_name             object
choice_description    object
item_price            object
dtype: object

In [18]:
order_details.describe()

          order_id     quantity
count  4622.000000  4622.000000
mean    927.254868     1.075725
std     528.890796     0.410186
min       1.000000     1.000000
25%     477.250000     1.000000
50%     926.000000     1.000000
75%    1393.000000     1.000000
max    1834.000000    15.000000

## chapter 3- pandas data structure
* 1D-series
* 2D-dataframe

In [19]:
import pandas as pd

In [20]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\deepak\appdata\local\programs\python\python310\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.22.4 in c:\users\deepak\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: pytz>=2020.1 in c:\users\deepak\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2026.3.post1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\deepak\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in c:\users\deepak\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in c:\users\deepak\appdata\local\programs\python\python310\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 23.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [21]:
pd.Series(data=[1,2,5,6,"$4.5"])

0       1
1       2
2       5
3       6
4    $4.5
dtype: object

In [22]:
pd.DataFrame({"name":["raj","dee","rahul","gokul","mohan"],
                     "maths":[78,89,99,89,98],
                     "science":[99,89,98,97,96]})

    name  maths  science
0    raj     78       99
1    dee     89       89
2  rahul     99       98
3  gokul     89       97
4  mohan     98       96

## chapter -4 filtering & selection & sorting

In [23]:
euro_data=pd.read_csv("Euro_2012_stats_TEAM.csv")
euro_data

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,...,13,81.3%,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,...,9,60.1%,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,...,10,66.7%,25,38,8,4,0,7,7,15
3,England,5,11,18,50.0%,17.2%,40,0,0,0,...,22,88.1%,43,45,6,5,0,11,11,16
4,France,3,22,24,37.9%,6.5%,65,1,0,0,...,6,54.6%,36,51,5,6,0,11,11,19
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,...,10,62.6%,63,49,12,4,0,15,15,17
6,Greece,5,8,18,30.7%,19.2%,32,1,1,1,...,13,65.1%,67,48,12,9,1,12,12,20
7,Italy,6,34,45,43.0%,7.5%,110,2,0,0,...,20,74.1%,101,89,16,16,0,18,18,19
8,Netherlands,2,12,36,25.0%,4.1%,60,2,0,0,...,12,70.6%,35,30,3,5,0,7,7,15
9,Poland,2,15,23,39.4%,5.2%,48,0,0,0,...,6,66.7%,48,56,3,7,1,7,7,17
10,Portugal,6,22,42,34.3%,9.3%,82,6,0,0,...,10,71.5%,73,90,10,12,0,14,14,16
11,Republic of Ireland,1,7,12,36.8%,5.2%,28,0,0,0,...,17,65.4%,43,51,11,6,1,10,10,17
12,Russia,5,9,31,22.5%,12.5%,59,2,0,0,...,10,77.0%,34,43,4,6,0,7,7,16
13,Spain,12,42,33,55.9%,16.0%,100,0,1,0,...,15,93.8%,102,83,19,11,0,17,17,18
14,Sweden,5,17,19,47.2%,13.8%,39,3,0,0,...,8,61.6%,35,51,7,7,0,9,9,18
15,Ukraine,2,7,26,21.2%,6.0%,38,0,0,0,...,13,76.5%,48,31,4,5,0,9,9,18

In [24]:
filter_data=euro_data[["Team","Goals","Yellow Cards","Red Cards"]]
filter_data

                   Team  Goals  Yellow Cards  Red Cards
0               Croatia      4             9          0
1        Czech Republic      4             7          0
2               Denmark      4             4          0
3               England      5             5          0
4                France      3             6          0
5               Germany     10             4          0
6                Greece      5             9          1
7                 Italy      6            16          0
8           Netherlands      2             5          0
9                Poland      2             7          1
10             Portugal      6            12          0
11  Republic of Ireland      1             6          1
12               Russia      5             6          0
13                Spain     12            11          0
14               Sweden      5             7          0
15              Ukraine      2             5          0

## 4.1 top 5 yellow card

In [25]:
filter_data.sort_values(by="Yellow Cards",ascending=False).head()

        Team  Goals  Yellow Cards  Red Cards
7      Italy      6            16          0
10  Portugal      6            12          0
13     Spain     12            11          0
0    Croatia      4             9          0
6     Greece      5             9          1

## 4.2 list team which as got red cards

In [26]:
filter_data[filter_data["Red Cards"]==1]

                   Team  Goals  Yellow Cards  Red Cards
6                Greece      5             9          1
9                Poland      2             7          1
11  Republic of Ireland      1             6          1

## 4.3 list the teamwhich has got more than 8 yellow cards

In [27]:
filter_data[filter_data["Yellow Cards"]>=0]

                   Team  Goals  Yellow Cards  Red Cards
0               Croatia      4             9          0
1        Czech Republic      4             7          0
2               Denmark      4             4          0
3               England      5             5          0
4                France      3             6          0
5               Germany     10             4          0
6                Greece      5             9          1
7                 Italy      6            16          0
8           Netherlands      2             5          0
9                Poland      2             7          1
10             Portugal      6            12          0
11  Republic of Ireland      1             6          1
12               Russia      5             6          0
13                Spain     12            11          0
14               Sweden      5             7          0
15              Ukraine      2             5          0

## chapter -5 how to deal with missing values

In [28]:
proitbridge_emp_data=pd.read_csv("employee_data.csv")
proitbridge_emp_data

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech      NaN  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
6      NaN  40.0         IT  64000.0  10-09-2022
7    Nasir  31.0    IT Tech      NaN  12-11-2020

## Level 1 data cleaning

## Always recommended: i will call to my client & check with him if he can give the right data_great!!!
 incase,client is asking us to perform the data clearing operation

#### step1: remove duplicate values

In [29]:
proitbridge_empa_data=proitbridge_emp_data.drop_duplicates(inplace=True)
proitbridge_emp_data

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech      NaN  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
6      NaN  40.0         IT  64000.0  10-09-2022

#### step 2- find out the null entries

In [30]:
proitbridge_emp_data.isnull().sum()

Name          1
Age           1
Department    0
Salary        1
Join_Date     0
dtype: int64

In [31]:
proitbridge_emp_data.dropna(inplace=True)
proitbridge_emp_data

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023

In [32]:
proitbridge_emp_data.shape

(4, 5)

#### step 3 Record in document
* Step3: Record in a Document

Client gave totally 7 Obseravations out of which 3 entries are removed because those records do not have complete information.

* Step 4: Get Approval

Send this to Client and get the approval to proceed for Model Building or Model Training

In [33]:
proitbridge_emp_data.isnull().sum()

Name          0
Age           0
Department    0
Salary        0
Join_Date     0
dtype: int64

# level-2 data cleaning

In [34]:
import pandas as pd

In [35]:
employee_added_details=pd.read_csv("employee_data.csv")
employee_added_details

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech      NaN  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
6      NaN  40.0         IT  64000.0  10-09-2022
7    Nasir  31.0    IT Tech      NaN  12-11-2020

 ## step -1: Drop duplicates

In [36]:
employee_added_details.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7     True
dtype: bool

In [37]:
employee_added_details.drop_duplicates(inplace=True)
employee_added_details

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech      NaN  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
6      NaN  40.0         IT  64000.0  10-09-2022

## step 2- Identity null observations

In [38]:
employee_added_details.isna().sum()

Name          1
Age           1
Department    0
Salary        1
Join_Date     0
dtype: int64

## step 3- Go for best imputation

In [39]:
employee_added_details["Department"].unique()

array(['Ops', 'IT Tech', 'Support', 'IT'], dtype=object)

In [40]:
employee_added_details["Department"]

0        Ops
1    IT Tech
2    Support
3        Ops
4    Support
5    Support
6         IT
Name: Department, dtype: object

In [41]:
employee_added_details[employee_added_details["Department"]=="Support"]

      Name   Age Department   Salary   Join_Date
2  Mathiew   NaN    Support  58000.0  15-01-2025
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023

In [42]:
employee_added_details[employee_added_details["Department"]=="IT"]

  Name   Age Department   Salary   Join_Date
6  NaN  40.0         IT  64000.0  10-09-2022

In [43]:
employee_added_details[employee_added_details["Department"]=="IT Tech"]

    Name   Age Department  Salary   Join_Date
1  Nasir  31.0    IT Tech     NaN  12-11-2020

In [44]:
employee_added_details[employee_added_details["Department"]=="Ops"]

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
3  Gilbert  29.0        Ops  60000.0  21-05-2021

## Data analytics task-1
1. impute the relavent value in the salary column whenever it is NaN.Based on department filtering
2. impute mathiew age is 27

In [45]:
employee_added_details[employee_added_details["Department"]=="Support"]

      Name   Age Department   Salary   Join_Date
2  Mathiew   NaN    Support  58000.0  15-01-2025
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023

In [46]:
employee_added_details[(employee_added_details["Age"]=="Support") & (employee_added_details["Salary"].fillna(6.0000)) == 60000]

Empty DataFrame
Columns: [Name, Age, Department, Salary, Join_Date]
Index: []

In [47]:
employee_added_details.groupby("Department")["Salary"].transform(lambda x:x.fillna(x.mean()))

0    60000.0
1        NaN
2    58000.0
3    60000.0
4    61000.0
5    72000.0
6    64000.0
Name: Salary, dtype: float64

In [48]:
employee_added_details.groupby("Department")["Salary"].transform("Age")
employee_added_details

ValueError: 'Age' is not a valid function name for transform(name)

In [49]:
employee_added_details.transform(lambda x:x.fillna(x.mean))

,Name,Age,Department,Salary,Join_Date
0,Rajesh,29.0,Ops,60000.0,21-05-2023
1,Nasir,31.0,IT Tech,<bound method Series.mean of 0 60000.0\n1 ...,12-11-2020
2,Mathiew,<bound method Series.mean of 0 29.0\n1 3...,Support,58000.0,15-01-2025
3,Gilbert,29.0,Ops,60000.0,21-05-2021
4,Kevin,28.0,Support,61000.0,30-07-2024
5,Navin,35.0,Support,72000.0,19-08-2023
6,<bound method Series.mean of 0 Rajesh\n1 ...,40.0,IT,64000.0,10-09-2022